name: spotlight_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  table_calendar: ^3.2.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.2.0
  provider: ^6.1.2


flutter:
  uses-material-design: true
  assets:
    - resources/erica-han.png
    - resources/hamilton.png
    - resources/james-denver.png
    - resources/john-brisbane.png
    - resources/logo.png
    - resources/mike-johnson.png
    - resources/samantha-young.png
    - resources/the-eras-tour.png
